#!/usr/bin/env bash
cur=$(dirname "$(readlink -f $0)")

# certs generated by
# easyrsa init-pki
# easyrsa --batch "--req-cn=k8s-test-cert@`date +%s`" build-ca nopass
# easyrsa --subject-alt-name="IP:192.168.0.1,IP:127.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster,DNS:kubernetes.default.svc.cluster.local"  --days=10000 build-server-full server nopass
